// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6PCIADMV0ctZb3J35VtFok2mQRW5qM-U',
    appId: '1:300747451569:web:22a6aec39232d318aac690',
    messagingSenderId: '300747451569',
    projectId: 'lovatra-labs33',
    authDomain: 'lovatra-labs33.firebaseapp.com',
    storageBucket: 'lovatra-labs33.firebasestorage.app',
    measurementId: 'G-FNEB79F0L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzamNJzX_44lMGp8Cp9Fn63NvhyZEXaqg',
    appId: '1:300747451569:android:44c59a4a02d4be43aac690',
    messagingSenderId: '300747451569',
    projectId: 'lovatra-labs33',
    storageBucket: 'lovatra-labs33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4WreDMQmp4cBC5GWWawwv2Okp4v8vQPk',
    appId: '1:300747451569:ios:ba79203c9be5756caac690',
    messagingSenderId: '300747451569',
    projectId: 'lovatra-labs33',
    storageBucket: 'lovatra-labs33.firebasestorage.app',
    iosClientId: '300747451569-epftncustg64oa84ull7l9567t3u8kln.apps.googleusercontent.com',
    iosBundleId: 'com.example.testCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4WreDMQmp4cBC5GWWawwv2Okp4v8vQPk',
    appId: '1:300747451569:ios:ba79203c9be5756caac690',
    messagingSenderId: '300747451569',
    projectId: 'lovatra-labs33',
    storageBucket: 'lovatra-labs33.firebasestorage.app',
    iosClientId: '300747451569-epftncustg64oa84ull7l9567t3u8kln.apps.googleusercontent.com',
    iosBundleId: 'com.example.testCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6PCIADMV0ctZb3J35VtFok2mQRW5qM-U',
    appId: '1:300747451569:web:c277d536ca7d321baac690',
    messagingSenderId: '300747451569',
    projectId: 'lovatra-labs33',
    authDomain: 'lovatra-labs33.firebaseapp.com',
    storageBucket: 'lovatra-labs33.firebasestorage.app',
    measurementId: 'G-25VHH58LKT',
  );
}
